Astractl 13710/configmap interface
theotw/natssync pull request #63
Opened 2022-01-06 22:49 UTC by jharrod

Adds an Persistence interface implementation that uses configmaps to store data.

This is very similar to the file_key_store's implementation of this interface, except we use the k8s API to update/create new data.

The one downside is that configmap updates take time to propagate to the pods (1.5 - 2 minutes is the worst I've seen). For what we're using this for I don't think it's an issue. @bmason42 fyi

I've added some tests, again, adapted from the file_key_store's tests. I've added a instructions in comments on how to run them. They require a specific setup and have to run in a pod on the cluster. It's easy once you know what to do.

2022-01-07 19:07 UTC, bmason42 requested changes

2022-01-07 19:08 UTC, jharrod commented on pkg/persistence/configmap/configmap_key_store.go
> +	microSecs := time.Now().UnixNano()
Good catch. It started as micro.

2022-01-07 19:10 UTC, jharrod commented on pkg/persistence/configmap/configmap_key_store_test.go
> +func TestFileKeyStore(t *testing.T) {
That would be awesome

2022-01-07 19:13 UTC, jharrod commented on pkg/persistence/configmap/configmap_test_pod.yaml
> +        - name: cluster-agent-configmap-volume
Good catch. I'll change it to /configmap-data

2022-01-07 19:16 UTC, jharrod commented on pkg/persistence/configmap/configmap_key_store_test.go
> +How to run these tests:
Maybe? I was following how `pkg/persistence/configmap/configmap_key_store_test.go` did it. 
I'm still new to the repo so just let me know where you think it should go

2022-01-11 21:40 UTC, jharrod commented on Makefile
> +	go test ${LDFLAGS} ${COVERPKG} -c -o out/configmap_keystore_${GOARCH}_${GOOS}.test pkg/persistence/configmap/configmap_key_store_test.go
Can you clarify? I'm confused

2022-01-11 21:54 UTC, bmason42 approved these changes

2022-01-11 21:54 UTC, bmason42 commented on Makefile
> +	go test ${LDFLAGS} ${COVERPKG} -c -o out/configmap_keystore_${GOARCH}_${GOOS}.test pkg/persistence/configmap/configmap_key_store_test.go
the way the test run,  I think this will be run as a unit test.  There is a /test directory for non-unit tests that need setup to run

2022-01-11 21:54 UTC, bmason42 commented on pkg/persistence/configmap/configmap_key_store_test.go
> +func TestFileKeyStore(t *testing.T) {
Well, I think so too, but your layer needs k8s so I dont think it will be as easy as I thought.  But maybe a L2 test

2022-01-13 20:22 UTC, merged